---

dependencies:
  - "{{ playbook_dir }}/../prometheus-exporters-common"
galaxy_info:
  role: "{{ playbook_dir }}/roles/"
  author: Shabbir Kagalwala
  description: Deploy Prometheus IPSec Exporter
  license: GPLv2
  min_ansible_version: 2.0
  platforms:
  - name: Debian
    versions:
    - jessie
    - wheezy
    - stretch
  - name: Ubuntu
    versions:
    - trusty
    - xenial
  - name: EL
    versions:
    - 5
    - 6
    - 7
  galaxy_tags:
  - monitoring
