---

- name: download prometheus ipsec exporter binary
  get_url:
    url: "{{ prometheus_ipsec_exporter_url }}"
    dest: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_ipsec_exporter_release_name }}.tar.gz"

- name: create directory to extract executable
  file:
    path: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_ipsec_exporter_release_name }}"
    state: directory

- name: unarchive binary tarball
  unarchive:
    copy: no
    src: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_ipsec_exporter_release_name }}.tar.gz"
    dest: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_ipsec_exporter_release_name }}"
    creates: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_ipsec_exporter_release_name }}/{{ prometheus_ipsec_exporter_release_name }}"
  register: prometheus_ipsec_exporter_updated
  notify:
    - restart ipsec exporter

- name: rename executable to omit version
  command: mv "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_ipsec_exporter_release_name }}/ipsec_prometheus" "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_ipsec_exporter_release_name }}/ipsec_exporter"


- name: update group and owner for files
  file:
    path: "{{ prometheus_ipsec_exporter_release_name }}"
    recurse: yes
    owner: "{{ prometheus_exporters_common_user }}"
    group: "{{ prometheus_exporters_common_group }}"
  when: prometheus_ipsec_exporter_updated | changed

- name: create symlink to the current release
  file:
    src: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_ipsec_exporter_release_name }}"
    path: "{{ prometheus_exporters_common_root_dir }}/ipsec_exporter_current"
    state: link

- name: create systemd service unit
  template:
    src: etc/systemd/system/prometheus-ipsec-exporter.service.j2
    dest: /etc/systemd/system/prometheus-ipsec-exporter.service
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'systemd'
  notify:
    - reenable ipsec exporter service
    - restart ipsec exporter

- name: Looking which version of upstart is install
  command: initctl version
  when: ansible_service_mgr == 'upstart'
  register: upstart_version

- name: create init service unit
  template:
    src: etc/init/prometheus-ipsec-exporter.conf.j2
    dest: /etc/init/prometheus-ipsec-exporter.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'upstart'
  notify:
    - reinit ipsec exporter
    - restart ipsec exporter

- name: create sysvinit service unit
  template:
    src: etc/init.d/prometheus-ipsec-exporter.j2
    dest: /etc/init.d/prometheus-ipsec-exporter
    owner: root
    group: root
    mode: 0755
  when: ansible_service_mgr == 'sysvinit'
  notify:
    - restart ipsec exporter

- meta: flush_handlers

- name: ensure prometheus ipsec exporter service is enabled and started
  service:
    name: prometheus-ipsec-exporter
    state: started
    enabled: yes
