---

- name: reenable ipsec exporter service
  command: systemctl reenable prometheus-ipsec-exporter.service

- name: reinit ipsec exporter
  command: initctl reload-configuration

- name: restart ipsec exporter
  service:
    name: prometheus-ipsec-exporter
    state: restarted
